# Generated by Django 4.0.2 on 2022-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivors',
            name='age',
            field=models.IntegerField(),
        ),
    ]
